language: go
sudo: false

go:
 - 1.5.3
 - 1.6

# Gracefully handle developer forks
install: |
    MANTLE_DIR="${GOPATH}/src/github.com/coreos/mantle"
    if [[ "${TRAVIS_BUILD_DIR}" != "${MANTLE_DIR}" ]]; then
        mkdir -p "${MANTLE_DIR%/*}"
        mv "${TRAVIS_BUILD_DIR}" "${MANTLE_DIR}"
        export TRAVIS_BUILD_DIR="${MANTLE_DIR}"
        cd "${TRAVIS_BUILD_DIR}"
    fi

script:
  - bash -x ./build
  - bash -x ./test
