language: go
##sudo: false
sudo: required

go:
 - 1.5.3
 - 1.6

# Gracefully handle developer forks
install: |
    MANTLE_DIR="${GOPATH}/src/github.com/coreos/mantle"
    if [[ "${TRAVIS_BUILD_DIR}" != "${MANTLE_DIR}" ]]; then
        mkdir -p "${MANTLE_DIR%/*}"
        mv "${TRAVIS_BUILD_DIR}" "${MANTLE_DIR}"
        export TRAVIS_BUILD_DIR="${MANTLE_DIR}"
        cd "${TRAVIS_BUILD_DIR}"
    fi

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq lsb-release
 - lsb_release -da
 - sudo apt-get install -y -qq gcc-aarch64-linux-gnu
## - sudo apt-get install -y -qq aptitude
## - ls /usr/bin
## - sudo aptitude install -y gcc-aarch64-linux-gnu

script:
##  - bash -x ./build
##  - bash -x ./test
 - ls /usr/bin/aa*
 - echo $PATH
 - sudo find "aarch64-linux-gnu-gcc" /usr | grep "aarch64-linux-gnu-gcc"
 - aarch64-linux-gnu-gcc --help

after_script:
 - sudo apt-get remove gcc-aarch64-linux-gnu
 - sudo apt-get remove lsb-release
## - sudo aptitude remove gcc-aarch64-linux-gnu
## - sudo apt-get remove -y -qq aptitude