language: go
##sudo: false
sudo: required

go:
 - 1.5.3
 - 1.6

# Gracefully handle developer forks
install: |
    MANTLE_DIR="${GOPATH}/src/github.com/coreos/mantle"
    if [[ "${TRAVIS_BUILD_DIR}" != "${MANTLE_DIR}" ]]; then
        mkdir -p "${MANTLE_DIR%/*}"
        mv "${TRAVIS_BUILD_DIR}" "${MANTLE_DIR}"
        export TRAVIS_BUILD_DIR="${MANTLE_DIR}"
        cd "${TRAVIS_BUILD_DIR}"
    fi

before_script:
 - bash -x cat /etc/lsb-release
 - bash -x sudo apt-get update -qq
 - bash -x sudo apt-get install -y -qq gcc-aarch64-linux-gnu

script:
##  - bash -x ./build
##  - bash -x ./test
  - bash -x aarch64-linux-gnu-gcc --help

after_script:
 - bash -x sudo aptitude remove gcc-aarch64-linux-gnu